image: openjdk:8

pipelines:
  default:
    - step:
        name: BitBucket Pipeline SkEmail
        deployment: test
        caches:
          - gradle
          - gradlewrapper
        script:
          - bash ./gradlew shadowjar
          - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"./build/libs/SkEmail-1.5-all.jar"
          
definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper 