name: SkEmail
description: Send email to someone in real life!
author: Olyno
version: "1.8"
main: com.olyno.skemail.SkEmail
depend:
  - Skript
commands:
  skemail:
    description: All commands from SkEmail.