name: SkEmail
description: Send email to someone in real life!
author: AlexLew
version: 1.5
main: com.alexlew.skemail.SkEmail
depend: [Skript]
commands:
    skemail:
        description: All commands from SkEmail.